### ISSUE TITLE
Replication having probelm.

### ISSUE THREAD

**Issue by Aliktk** [arnoweng/CheXNet#41]
Hello, Great work. Here I just want to discuss that the requirements are fulfilled but still getting errors in model Unexpected key(s) in state_dict.
Please update the readme that how a newbie can run them and retrain or test the model and get the AUC and eval parameters.
Thanks

**Comment by cmaBiomed** [comment]
Hi, newbie here. I am running into this exact problem, and I can't solve it. I have done exactly as the 'README.md' file explains; however, I cannot 'run'main.py' without these errors:
`C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=DenseNet121_Weights.IMAGENET1K_V1`. You can also use `weights=DenseNet121_Weights.DEFAULT` to get the most up-to-date weights.   
  warnings.warn(msg)
=> loading checkpoint
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\Proyectos\CheXNet-master\model.py", line 129, in <module>
    main()
  File "c:\Users\PC\Desktop\Proyectos\CheXNet-master\model.py", line 40, in main
    model.load_state_dict(checkpoint['state_dict'])
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DataParallel:
        Missing key(s) in state_dict: "module.densenet121.features.denseblock1.denselayer1.norm1.weight", "module.densenet121.features.denseblock1.denselayer1.norm1.bias", "module.densenet121.features.denseblock1.denselayer1.norm1.running_mean", `
That last part goes on for a long time.´
I think there is a problem with accessing the model path and some problems with the Python and Cuda versions, though those don't seem to be much of a deal as the program runs anyway until it reaches line 40.
Help would be greatly appreciated. I am working on a project and made an account just so I could post this question.
Thanks in advance.
