### ISSUE TITLE
Run model.py at a strange position

### ISSUE THREAD

**Issue by aa210682** [arnoweng/CheXNet#9]
I have already download the images and put then to the right position.
After this step , I run model.py.
But the process stop at a strange position.

```
root@fd1a0b35acfd:/CheXNet# python model.py
=> loading checkpoint
=> loaded checkpoint

```
The process is stop .
Can anyone help me to solve this problem??
Thank you very much

**Comment by stoicdataguy** [comment]
@aa210682 I think you are running into the same problem as i was. If you have followed pytorch installation for conda, then please check its version using.
`
import torch;
print (torch.__version__);
`
I found out that conda provides version 0.12 . Instead, try pip which gives you the latest 0.3 version.

What actually happens is that it throws error showing torchvison.transforms doesnot have 'Resize' or 'TenCrop' module. This problem will be resolved on updating your pytorch library.

![screen shot 2018-01-29 at 1 09 49 pm](https://user-images.githubusercontent.com/16842872/35519407-21967806-053a-11e8-8f28-2dfada43df4d.png)

**Comment by billhhh** [comment]
@AkhilPunia thx for providing your solution, I have the same problem as aa210682's. I have checked my version of pytorch, it is already in 0.3.0

**Comment by stoicdataguy** [comment]
@billhhh If you are getting an error code please post it here if not, then i suggest you try running a jupyter notebook for step by step execution.

**Comment by billhhh** [comment]
@AkhilPunia Thx for the advice, not an error code, just stuck here. I tried waiting, but it stucked here like forever

![image](https://user-images.githubusercontent.com/7709725/35565855-2dd6c8ee-05fa-11e8-89a6-f9e9cfa7ddba.png)

**Comment by stoicdataguy** [comment]
@billhhh You can have a look at my notebook .
[Model_Test_Prediction.pdf](https://github.com/arnoweng/CheXNet/files/1677608/Model_Test_Prediction.pdf)

Ok, so if your code seems to be stuck at this step, it might not even be an issue because the 'model.eval()' takes a significant amount of time. I am using a Tesla K80 and it took around 10 minutes for me. So, that is completely normal. You can check if your GPU is running by using 'nvidia-smi', if you are not using a GPU then its no wonder why the code is stuck.

**Comment by billhhh** [comment]
@AkhilPunia Thx, man
